#!/usr/bin/env bash
# configures an Nginx server to listen on port 80

# remove the default Nginx configration file
rm /etc/nginx/sites-available/default

# configure nginx to listen on port 80 for all active Ipv4 Ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
